import { Opinion } from '../features/vote/types/opinion';

export const TopOpinionDummy: Opinion[] = [
  {
    id: 1,
    memberId: 1,
    nickname: '김철수',
    profileImageUrl: 'https://www.neupinion.com/profile/1',
    createdAt: '2024-05-02T03:26:57.897Z',
    isReliable: true,
    paragraphId: 20,
    paragraphContent: '이 부분이 문제가 되는 이유는...',
    content: '이런 부분은 문제가 있어요!',
    likeCount: 10,
    isLiked: true,
  },
  {
    id: 1,
    memberId: 2,
    nickname: '김철수',
    profileImageUrl: 'https://www.neupinion.com/profile/1',
    createdAt: '2024-05-02T03:26:57.897Z',
    isReliable: true,
    paragraphId: 20,
    paragraphContent: '이 부분이 문제가 되는 이유는...',
    content: '이런 부분은 문제가 있어요!',
    likeCount: 10,
    isLiked: true,
  },
  {
    id: 1,
    memberId: 3,
    nickname: '김철수',
    profileImageUrl: 'https://www.neupinion.com/profile/1',
    createdAt: '2024-05-02T03:26:57.897Z',
    isReliable: true,
    paragraphId: 20,
    paragraphContent: '이 부분이 문제가 되는 이유는...',
    content: '이런 부분은 문제가 있어요!',
    likeCount: 10,
    isLiked: true,
  },
  {
    id: 1,
    memberId: 4,
    nickname: '김철수',
    profileImageUrl: 'https://www.neupinion.com/profile/1',
    createdAt: '2024-05-02T03:26:57.897Z',
    isReliable: true,
    paragraphId: 20,
    paragraphContent: '이 부분이 문제가 되는 이유는...',
    content: '이런 부분은 문제가 있어요!',
    likeCount: 10,
    isLiked: true,
  },
  {
    id: 1,
    memberId: 5,
    nickname: '김철수',
    profileImageUrl: 'https://www.neupinion.com/profile/1',
    createdAt: '2024-05-02T03:26:57.897Z',
    isReliable: true,
    paragraphId: 20,
    paragraphContent: '이 부분이 문제가 되는 이유는...',
    content: '이런 부분은 문제가 있어요!',
    likeCount: 10,
    isLiked: true,
  },
];
